### ISSUE TITLE
Build order is very inconvenient

### ISSUE THREAD

**Issue by WreckedAvent** [madskristensen/WebCompiler#124]
I am using web compiler with TFS 2013, in attempt to avoid checking in .css files when there are .less files checked in.

I noticed web compiler was compiling extremely late in the build process, and not getting included in the drop folder, so I decided to try and add a build target to the csproj to run after the build to try and capture the output. Unfortunately, this is still too early.

I saw #73, but the issue is still present for me using version 1.6.217. Here is the relevant parts of the build log:

```
         Copying file from "Scripts\<snip>" to "C:\Builds\1\<snip>".
       AfterBuild:
         Testing if web compile has run
       WebCompile:
         
         WebCompiler: Begin compiling compilerconfig.json
```

**Comment by madskristensen** [comment]
Did you update the BuildWebCompiler NuGet package? I believe the issue has been fixed in the later versions

**Comment by WreckedAvent** [comment]
I had the issue initially with 1.6.217. I have updated to 1.6.219, but the issue persists. 

```
    17>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreCompile:
         C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Csc.exe .. <snip> 
     9>AfterBuild:
         Testing if web compile has run
       WebCompile:         
         WebCompiler: Begin compiling compilerconfig.json
         WebCompiler installing updated versions of the compilers...
```

**Comment by madskristensen** [comment]
Are you sure you updated the nuget package and not just the extension?

**Comment by WreckedAvent** [comment]
Here's what I did to update, through the nuget package manager in 2015:

![image](https://cloud.githubusercontent.com/assets/2645770/10396715/00f74604-6e72-11e5-998f-a673fbccdeef.png)

**Comment by madskristensen** [comment]
Ok, you should be good then. In the package folder under **BuildBundlerMinifier** there should be a file calld _BuildBundlerMinifier.targets_ under the _build_ subfolder. 

It has this in it:

```xml
<PropertyGroup>
    <BuildDependsOn>
        $(BuildDependsOn);
        BundleMinify
    </BuildDependsOn>
</PropertyGroup>
```
What it does is that it runs the _BundleMinify_ task after the regular build tasks has run. Does it fix your problem if you switch them around like this?

```xml
<PropertyGroup>
    <BuildDependsOn>
        BundleMinify;
        $(BuildDependsOn)
    </BuildDependsOn>
</PropertyGroup>
```
I've been thinking of switching them but I'm not fully aware of the consequences for everybody using it.

**Comment by WreckedAvent** [comment]
In `\packages\BuildWebCompiler.1.6.219\build\` I was able to find a file called `BuildWebCompiler.targets`. I am not using the **BuildBundlerMinifier**, so I assume you meant to go to the **BuildWebCompiler** one.

Anyway, in that file I changed:

```xml
    <PropertyGroup>
        <BuildDependsOn>
            $(BuildDependsOn);
            WebCompile
        </BuildDependsOn>
    </PropertyGroup>
```

to

```xml
   <PropertyGroup>
        <BuildDependsOn>
            WebCompile;
            $(BuildDependsOn)
        </BuildDependsOn>
    </PropertyGroup>
```

**This appears to correct the build order correctly** for my *local* building. I am unable to test it on the TFS build server since it just gets the latest packages and doesn't persist any changes I make to them.

**Comment by madskristensen** [comment]
Sorry, I meant **BuildWebCompiler** :)

That's great. I'll make the change to the targets file

**Comment by madskristensen** [comment]
The updated NuGet package version 1.6.220 should be ready within the next couple of minutes with the fix

**Comment by WreckedAvent** [comment]
Thanks for the fix!

As a happy side-effect, this appears to make web compiler run pretty early in the build process. On my TFS2013 build server, it now runs before TFS copies things to the drop folder, so I might be able to skip the after-build step entirely and just have the css files included in the csproj (but not checked into source).
