### ISSUE TITLE
Error handling and missing errors

### ISSUE THREAD

**Issue by RaptorCZ** [madskristensen/WebCompiler#80]
I have less file to compile. I have compilerconfig.json with simple definition (input and output). When I try to execute compile action, it says in status bar "Error compiling "xxx.less". See Error List for details". But there is no error in error list. How can I get this message? Any way how to redirect messages to Output window?

**Comment by madskristensen** [comment]
Can you please share your less file?

**Comment by RaptorCZ** [comment]
Check this project and try to compile using compilerconfig.json file.

http://raptor.cestiny.cz/Temp/LessCompileTest_03.zip

**Comment by madskristensen** [comment]
I get this error:

![compilertest](https://cloud.githubusercontent.com/assets/1258877/9361331/c1594898-464f-11e5-9982-024c0f59c73e.png)

Have you tried the latest version of the extension from here? http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by RaptorCZ** [comment]
Yes, I have the latest version 1.2.132 and this is what I see:
![noerror](https://cloud.githubusercontent.com/assets/4438783/9361928/239460a8-469e-11e5-856c-c91ffd60caf1.JPG)
There is no error in error list, but there is info about 0 of 1 Error.

**Comment by madskristensen** [comment]
Make sure you show errors for both "Build  + Intellisense"

![compilertest2](https://cloud.githubusercontent.com/assets/1258877/9362935/50adea32-4658-11e5-9670-e6021d8f4aa3.png)

**Comment by RaptorCZ** [comment]
Well, I have to apologize, I sent you wrong test project, with wrong paths in less files. It is error you got. Please use this project instead:
http://raptor.cestiny.cz/Temp/LessCompileTest_04.zip

Well, ok, now I have enabled intellisense items and I see error. 
![err1](https://cloud.githubusercontent.com/assets/4438783/9363629/d8199fbc-46a7-11e5-9e16-ba9f643c0213.JPG)
But this error doesn't make sense to me. Whole less can be compiled using lessc and node and webessentials 2013. Mixin is defined and all is valid. So my first question is what is wrong in this compiler version?

And I have another question. On other PC I'm getting this error:
![err2](https://cloud.githubusercontent.com/assets/4438783/9363689/224a19d6-46a8-11e5-8d36-b708312c5788.JPG)

**Comment by madskristensen** [comment]
This is the compiler error message. I don't modify those. I don't know why it shows up under Intellisense or how to fix that. Perhaps @jaredpar knows how to change that?

**Comment by jaredpar** [comment]
@jasonmalinowski  should be able to answer that question.  I don't quite know how the error list differentiates here.

**Comment by RaptorCZ** [comment]
Ok, error log is just some kind of category, but what about error message and node error? If WC uses the same compiler as old WE2013, why I'm able to compile this less in WE and not in WC?

**Comment by jasonmalinowski** [comment]
@madskristensen, @jaredpar: not sure I understand the question here. "Intellisense" errors come from us providing errors directly via an API. "Build" errors are flowed from the build via the usual way (regexes or whatever.)

**Comment by madskristensen** [comment]
Thanks for clarifying @jasonmalinowski 

@RaptorCZ Something is wrong with node.exe on the path. Can you try to delete all the temp folders that looks like this `%localappdata%\Temp\WebCompiler1.2.134` and then try again. I can compile the fine just fine. It's not the compiler that is the issue, it is node.exe not being on the path

**Comment by RaptorCZ** [comment]
@jasonmalinowski Well, I understand difference between intellisense errors and build errors. Intellisense is provided on fly - continuous build. But building less file using recompile command should be in error log, not intellisence, because it is not something generated from VS continuous build. It is regular error.

@madskristensen Ok, deleted WebCompiler1.2.132 folder from temp, tried again, still the same error.

**Comment by RaptorCZ** [comment]
@madskristensen Well, seems that WebCompiler 1.2.134 fixes this error. Node works. Now I'm getting error with .clearfix as described on image above.

**Comment by RaptorCZ** [comment]
Well, seems that message from compiler is warning, not error!

```
C:\!\LessCompileTest\LessCompileTest\Styles>lessc MaxxCms.less > MaxxCms.css
extend ' .clearfix' has no matches
extend ' .clearfix' has no matches
```

CSS file is generated succesfully.

**Comment by RaptorCZ** [comment]
Well, but it is NOT fixed. This just moves compiler message from errors to warnings, but output is not saved to css file.

**Comment by madskristensen** [comment]
Did you try version 1.4 which I just released?

**Comment by RaptorCZ** [comment]
Yes, I did. Still the same. Displays warning but nothing is compiled to output file.
